version: '2.1'

services:
  reverse-proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - botsta-db
      - botsta-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

  botsta-db:
    image: postgres:${BOTSTA_DB_TAG}
    restart: always
    #ports:
      #- ${BOTSTA_DB_PORT}:5432
    volumes:
      -  ./mount/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${BOTSTA_DB_USER}
      POSTGRES_PASSWORD: ${BOTSTA_DB_PASSWORD}
      POSTGRES_DB: ${BOTSTA_DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BOTSTA_DB_USER} -d ${BOTSTA_DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  botsta-server:
    image: botsta-server:${BOTSTA_SERVER_TAG}
    #ports:
      #- ${BOTSTA_SERVER_PORT}:80
    build: 
      context: .
    depends_on: 
      botsta-db:
        condition: service_healthy
    links:
        - botsta-db
    environment:
      AutoMigrate: ${BOTSTA_SERVER_AUTO_MIGRATE}
      AppConfig__JwtIssuer: ${BOTSTA_SERVER_ISSUER}
      AppConfig__JwtAudience: ${BOTSTA_SERVER_AUDIENCE}
      AppConfig__JwtSecret: ${BOTSTA_SERVER_SECRET}
      AppConfig__TokenExpirationMinutes: ${BOTSTA_SERVER_TOKEN_EXPIRATION_MINUTES}
      AppConfig__RefreshTokenExpirationDays: ${BOTSTA_SERVER_REFRESH_TOKEN_EXPIRATION_DAYS}
      ConnectionStrings__DefaultConnection: ${BOTSTA_SERVER_CONNECTION_STRING}

